"""Finalize only after measured extraction, scoring and independent replay receipts."""
from run_motion import OUT,d,np,json,time,budget

def main():
    cap=budget();m=json.loads((OUT/'metrics.json').read_text());v=json.loads((OUT/'validation_metrics.json').read_text());g=json.loads((OUT/'adequacy_gate.json').read_text());check=json.loads((OUT/'verification.json').read_text());replay=json.loads((OUT/'independent_replay.json').read_text());spec=json.loads((OUT/'protocol.json').read_text());ident=json.loads((OUT/'identity.json').read_text())
    assert replay['metrics_exact'] and replay['prediction_max_abs']==0 and check['checkpoint_and_state_unchanged']
    def fmt(q):return f"{q['value']:.3f} [{q['ci95'][0]:.3f}, {q['ci95'][1]:.3f}]"
    def table(ms):
        lines=['|Arm|Event BA [95% CI]|Event AUC [95% CI]|Event-side BA [95% CI]|Event hits|Catch false positives|','|---|---|---|---|---|---|']
        for k,z in ms.items():
            if not isinstance(z,dict) or 'event_ba' not in z:continue
            lines.append(f"|{k}|{fmt(z['event_ba'])}|{fmt(z['event_auc'])}|{fmt(z['side_ba'])}|{z['event_hits']}/{z['events']}|{z['catch_false_positives']}/{z['catches']}|")
        return lines
    # Same-trial target report reference, with image-decoded cue, not true cue.
    meta=json.loads((OUT/'test_metadata.json').read_text());y=np.array([a['label'] for a in meta]);flow=np.load(OUT/'test_flow.npz');pred=np.load(OUT/'test_predictions.npz');thresholds=json.loads((OUT/'flow_thresholds.json').read_text());boot=np.load(OUT/'test_bootstrap.npz')['indices'];refs={}
    for name in ('full','endpoint3','window5'):
        score=pred['flow/'+name][np.arange(len(y)),flow['decoded_cue']];p=score>thresholds[name]
        refs[name]=dict(ba=d.ba(y,p),ci95=np.quantile([d.ba(y[r],p[r]) for r in boot],[.025,.975]).tolist(),threshold_degrees=thresholds[name],threshold_selected_for='any-event validation, not target-report optimization',cue_correct=int(sum(flow['decoded_cue'][i]==a['target_location'] for i,a in enumerate(meta))))
    d.dump(OUT/'target_report_reference.json',refs)
    lines=['# Motion-specific readout diagnostic — frozen selected2297','','## Decision and scope','',
      '**Analysis-decoder training only.** The original native task, stimuli, curriculum and deployed model were not modified. These readouts estimate physical motion events and changed side; this is not successful acquisition of the complete cue-conditioned task. No cloud or deployed-model optimizer was used.','',
      f"Raw-pixel adequacy gate: **{'PASS' if g['passed'] else 'FAIL'}**, fixed before fitting and before independent test generation. Train600 and validation150 are exact hash-verified rerenders of the prior adequacy train/validation movies; test300 is newly generated, disjoint from every prior saved movie.",'',
      f"Validation pixels: side BA **{fmt(v['pixels']['side_ba'])}**, event BA **{fmt(v['pixels']['event_ba'])}**, event AUC **{fmt(v['pixels']['event_auc'])}**. All seven prespecified criteria were evaluated without consulting test results.",'']
    if g['passed']:
        lines += [f"Fresh test pixels: side BA **{fmt(m['pixels']['side_ba'])}**, event BA **{fmt(m['pixels']['event_ba'])}**. Frozen early-CNN maps with the same displacement/comparison family: side BA **{fmt(m['trained']['side_ba'])}**, event BA **{fmt(m['trained']['event_ba'])}**.",'',
          '**The pixel control succeeded; the identical motion-comparison family did not transfer to frozen early-CNN maps.** The neural event classifier reports an event on every test movie, including every catch, and side decoding is not reliably above chance. This narrows the failure to the tested substrate/readout pairing rather than repeating the old raw-pixel probe failure. It does **not** prove that the CNN erased motion information: brightness/feature constancy, stride, nonlinear feature transformations, channel weighting and spatial support are not equivalent across substrates. No random encoder was included, so trained-weight effects cannot be separated from architectural effects.','',
          '**Next decision:** retain the frozen deployed observer and unchanged teaching. Close this bounded comparison; do not install this analysis decoder or infer an encoder lesion. If the neural readout underperforms despite the pixel control, the unresolved question is whether the frozen representation preserves usable motion under a representation-appropriate, independently calibrated comparison—not whether an external-history decoder already remedies the deployed task. Any further diagnostic requires a separately justified design and authorization.','']
    else:
        lines+=['**Stop:** the prespecified raw-pixel adequacy gate failed. No neural-feature diagnostic was executed. Do not infer encoder failure or add another probe under this authorization. The fresh pixel test below only characterizes this failed positive control and cannot reverse the gate.','']
    lines+=['## Fresh paired test','',f"Independent movies: {m['counts']['test']}; events {m['counts']['events']}, catches {m['counts']['catches']}; event-left {m['counts']['test_left']}, event-right {m['counts']['test_right']}. Native26/28-degree magnitudes, baseline12/20/28 transitions; original target/foil/catch sampling and renderer.",'']+table({k:z for k,z in m.items() if k in ('pixels','pixels/shuffled','trained','trained/shuffled','flow/full','flow/endpoint3','flow/window5')})
    lines+=['','## Paired differences','|Comparison|Event BA gain [95% CI]|Event AUC gain [95% CI]|Side BA gain [95% CI]|','|---|---|---|---|']
    for k,z in m['paired_gains'].items():lines.append(f"|{k}|{fmt(z['event_ba'])}|{fmt(z['event_auc'])}|{fmt(z['side_ba'])}|")
    lines+=['','## Native event-type breakdown','Counts are predicted **any physical event**, not cue-conditioned positive reports.','|Arm|Target-event detections|Foil-event detections|Catch false positives|','|---|---|---|---|']
    for k,z in m['native_event_breakdown'].items():lines.append('|'+k+'|'+'|'.join(f"{z[e]['predicted_events']}/{z[e]['n']}" for e in ('target','foil','catch'))+'|')
    head=m['native_target_report'];lines+=['','## Unchanged native-head and optical-flow target-report reference','',f"Frozen deployed head target-report BA: **{head['ba']:.3f} [{head['ci95'][0]:.3f}, {head['ci95'][1]:.3f}]**, evaluated on these same unchanged movies. Physical event/side readout scores above are different targets and cannot be directly called a deployed-head improvement.",'', '|Image observer + image-decoded cue|Target-report BA [95% CI]|','|---|---|']
    for k,z in refs.items():lines.append(f"|{k}|{z['ba']:.3f} [{z['ci95'][0]:.3f}, {z['ci95'][1]:.3f}]|")
    lines+=['','Flow uses the previously implemented sparse isolated-dot centroid matching, with known geometry, native dot mass/speed and external time windows. Target-report flow uses the **image-decoded cue**, with the already frozen any-event threshold; it is not a separately optimized target-report comparator. Full history is temporally privileged. Endpoint3 preserves the old reference; window5 matches this diagnostic’s total raw-frame access. No flow parameters or rendering were changed.','',
      '## Prespecified adequacy and minimal learned family','',spec['adequacy_gate'],'',
      '- Three iterations of robust multichannel first-order displacement least-squares (small-displacement SSD matching/Lucas–Kanade), fitting dx/dy from image/map spatial derivatives and temporal differences. Not the sparse optical-flow reference, and not a raw-pixel ridge baseline. Robust weights reduce replacement/boundary residuals; no dot IDs, angle truth, cue truth, event truth or changed-side truth enters descriptors or prediction APIs.',
      '- Each fixed patch independently yields eight features:1−direction cosine, absolute direction cross product, normalized-direction distance, relative speed difference, summed speeds, two normalized fit residuals and their absolute difference. A patch-shared balanced logistic decoder learns physical per-patch-change supervision from train only:8 standardized coefficients+intercept, fixedL2=1, fresh zero initialization and a single convex fit. Neural fit is separately fresh, not inherited from pixel or deployed weights. This is real **analysis-decoder training**, not model-free scoring.',
      '- One matched group-shuffled-supervision fit per representation, same features, fit budget and validation event-threshold rule. Complete two-patch label vectors are shuffled between independent movies. The side decision is right-probability minus left-probability>0; no true-event mask is used by predictions. Event mask is used only to score side on actual events. Event threshold0.05..0.95 is validation-only; no hyperparameter sweep or validation refit.',
      '- Raw input:three maps per phase, each a centered native three-frame grayscale stack, fixed29×29 patches. Corresponding CNN input:three64-channel7×7 maps per phase, from native full25×25 maps before first KDA, stride4; neural displacement multiplied by4 to express pixel units. Same eight descriptor dimensions and nine learned coefficients; same600 independent train groups/1200 patch rows. CNN receptive fields/global GroupNorm and spatial resolution/channel count remain unavoidable mismatches, not matched information content.',
      '- **Temporal access differs from the earlier adequacy report:** native stacks ending B+5/B+6/B+7 and B+13/B+14/B+15 expose five raw frames per phase. Both current arms receive the same six native stack times; external storage of both phases is privileged. The old saved3×3 CNN ROIs were not reused. This is not final-state-only decoding and cannot establish a deployed output-head remedy.',
      '- Both fixed spatial sites are always decoded. True cue is never used to choose a patch or comparator input. Native means are90° apart; patch-shared fitting does not use the other patch’s angle as an input, although event/side aggregation compares the two predicted patch probabilities.',
      '-1000 independent-movie bootstrap resamples, paired across arms,95% percentile intervals, conditional on one fitted decoder per condition and one frozen checkpoint. These intervals do not include training-sample/seed variation, representation-selection uncertainty or multiplicity correction. The validation gate is a pragmatic bounded go/no-go check, not a formal population test.',
      '- The single raw-pixel shuffled-supervision fit is strongly **below chance** for test side (BA0.201), not a clean chance-level null. A random training-label alignment can reverse the sign of a compact informative descriptor; this seeded control is not a many-permutation significance test. We retain it rather than flipping its scores or choosing a different shuffle. Raw-pixel adequacy also required absolute side/event performance and intervals above chance, independently of the gain over this shuffle.',
      '- A near-ceiling empirical interval ending1 is not certainty. Constant shuffled decisions can yield BA0.5 with a degenerate bootstrap interval; this is not evidence of equivalence. AUCs, confusion counts, native event/catch denominators and paired gains are retained in metrics.json.',
      '', '## Validation results','']+table(v)
    lines+=['','## Verification, recovery and artifacts','',
      f"Checkpoint: `{ident['checkpoint']}`; SHA256 `{ident['checkpoint_sha256']}`. State tensors and original model/renderer source hashes were verified unchanged after inference. Native renderer/capture parity includes rasters, labels, metadata and RNG state for all three durations.",
      '- Conditional neural extraction passed bit-exact native full-sequence-hook versus direct-block ROI parity at all six selected updates and unchanged hooked/native logits, for B12/B20/B28 (neural_hook_parity.json).' if g['passed'] else '- Neural extraction was not performed because adequacy failed.',
      '- Independent separate-process no-fit replay recalculated every train/validation/test descriptor from saved maps, every serialized real/shuffled prediction and test metric, train-only scaling, validation predictions, source/checkpoint/freeze hashes, all movie disjointness, and first three native test rasters/flow references. Prediction maximum absolute difference:0.',
      '- One execution encountered a strict-JSON serialization error on a NumPy boolean **after the two pixel fits but before gate receipt, neural extraction or test generation**. The failed source/log and recovery reason are preserved. A serialization-only fix reran the exact same deterministic extraction/two fits once under the **same original deadline**; no additional architecture, seed, criterion or candidate was tried. This repeated computation is included in the cap.',
      '- Background tracker null-exit notifications were not used as completion evidence: OS PID checks showed the recovery worker still live. Completion relies on completed numerical artifacts, hash verification and independent replay, not the tracker notification.',
      '- CPU only, torch2 threads/interop1, numerical libraries≤2threads, one extraction/fitting worker at a time. No MPS, cloud, main-model training, task alteration or existing90checkpoint restart. Replay/report complete inside the nonrenewable1800second budget; final_receipt.json gives final inclusive elapsed time.',
      '- Saved:protocol.json, budget.json, adequacy_gate.json, original/recovery logs, all train/validation/test raw or neural maps and descriptors, native metadata/movie hashes, exact fits.npz, shuffle permutation, selections/thresholds, pre-test freeze hashes, trial predictions, native head logits, full/endpoint/window5 flow angles, bootstrap indices, metrics, identity/parity/verification/replay receipts and source archive. Large artifacts remain local in this directory; prior analysis outputs are preserved.',
      '', '## Limits relative to the neuroscience SOP','',
      'This is a bounded mechanism-supporting failure diagnostic, not a new attention experiment. Cued-versus-uncued psychometric curves across validity, neutral/invalid cue manipulations, retention/inhibition/microstimulation and biological-circuit claims are **not measured here**. Native target/foil/catch counts and unchanged head scores are reported without relabeling foil events as physical catches. No timing/action policy was introduced; no reaction-time claim.',
      '', 'Reproduction:replay.py is no-fit and refuses execution beyond this run’s original deadline. Any later re-execution requires a newly authorized audit budget; do not edit/reset budget.json.']
    (OUT/'REPORT.md').write_text('\n'.join(lines)+'\n')
    journal=d.ROOT/'LabJournal/krauzlis-motion-readout-diagnostic.md'
    journal.write_text('# Motion-specific readout diagnostic — frozen selected2297\n\n'+ '\n'.join(lines[4:15])+'\n\nFull evidence/report:`SecondPass/SpatialReadout/SpatialConsolidation/KrauzlisFailureAudit/MotionReadoutDiagnostic/REPORT.md`.\n\nNo deployed updates, stimuli/curriculum changes or cloud. Fresh small analysis decoders only. The matched neural comparison remains subject to spatial/feature-constancy limitations; no encoder-erasure or deployed-remedy inference.\n')
    sources=['motion.py','run_motion.py','replay.py','finalize.py','test_motion.py','protocol.json']
    archive=OUT/'source_archive';archive.mkdir(exist_ok=True)
    for f in sources:(archive/f).write_bytes((OUT/f).read_bytes())
    assert time.time()<cap['deadline']
    d.dump(OUT/'final_receipt.json',dict(complete=True,elapsed_seconds=time.time()-cap['started'],within_original_cap=True,deadline=cap['deadline'],report_sha256=d.sha(OUT/'REPORT.md'),journal_sha256=d.sha(journal),verification_sha256=d.sha(OUT/'verification.json'),independent_replay_sha256=d.sha(OUT/'independent_replay.json'),artifact_hashes={p.name:d.sha(p) for p in OUT.iterdir() if p.is_file() and p.name not in ('final_receipt.json',)}))
    print('REPORT AND JOURNAL COMPLETE',json.dumps(json.loads((OUT/'final_receipt.json').read_text())|{'artifact_hashes':'retained on disk'}))

if __name__=='__main__':main()
