"""Finalize readable report from actual saved evidence within original cap."""
from pathlib import Path
import json,time
O=Path(__file__).resolve().parent
r=json.loads((O/'result.json').read_text()); b=json.loads((O/'budget.json').read_text()); v=json.loads((O/'saved_artifact_verification.json').read_text())
assert time.time()<b['deadline_unix'],'No cap extension for report computation'
of=r['overfit']; g=r['generalization']; old=r.get('initial_attempt',{}); perm=old.get('permuted_label_diagnostic',{})
lines=['# Conventional neural positive control — completed bounded experiment','',f"**{r['status']}.** One717,371-parameter learned spatiotemporal/axial-attention architecture; no KDA or GRU.",'','## Findings','',f"- Native32-trial fixed-set fit: CE{of['initial']['loss']:.6f} → {of['final']['loss']:.6f}; {round(of['final']['accuracy']*32)}/32 correct; {of['steps']}updates and {of['trial_presentations']}presentations. This is optimization/memorization evidence, not generalization.",'- The first recipe failed with a saturated dense GELU readout:93.75% exactly-zero hidden activations; initial loss0.728147 → chance-level0.693147. All initial gradient paths and parameter updates existed, so startup movement alone did not validate sustained optimization.','- One targeted correction reused the same architecture and same initial seed, reduced AdamW lr0.001→0.0001 and accumulated all32fixed scenes instead of8; the initial2-example update was removed. This succeeded at the fixed-set gate. The combined correction does not identify which changed optimizer detail was causal. No architecture search.','- Original failed-fit/permutation evidence is preserved in initial_attempt_result.json; localization is in failed_fit_localization.json.']
if perm:
    lines.append(f"- Fresh shuffled-label diagnostic under the original failed recipe: CE{perm['initial']['loss']:.6f} → {perm['final']['loss']:.6f}, BA{perm['final']['balanced_accuracy']:.4f}, {perm['steps']}updates. This is a capacity/optimization check, not a many-permutation generalization null.")
if g['executed']:
    lines += ['', '## Independent fresh-stream generalization','',f"Fresh model72002, fresh empty AdamW, and native920001/2/3 streams; no fixed-set weights transferred. {g['updates']}updates ×8 = **{g['train_episodes']}fresh training trials**. Native B12/B20/B28 exposures: {g['train_by_B']}; event counts: {g['train_events']}. AdamW lr0.0001,wd0.0001,clip5,effective8/micro2.",'',f"Validation300native trials; checkpoint chosen only by validationCE, including step0. Initial validationCE{g['initial_validation']['loss']:.6f}; terminalCE{g['terminal_validation']['loss']:.6f}. Choice frozen before test. Selected step{g['selected_step']}; fixed terminal step{g['terminal_step']}. Test600fresh scenes (200perB), never used to tune model/optimizer. Both endpoint roles are reported, not test-selected.",'','| Endpoint | BA (95% bootstrap CI) | AUC (95% bootstrap CI) | CE | TP / TN / FP / FN |','|---|---|---|---|---|']
    for role in ('selected','terminal'):
        m=g[role+'_test']; ci=m['stratified_physical_scene_bootstrap_95ci']; lo,hi=ci['balanced_accuracy']; al,ah=ci['auc']
        lines.append(f"| {role} | {m['balanced_accuracy']:.4f} [{lo:.4f},{hi:.4f}] | {m['auc']:.4f} [{al:.4f},{ah:.4f}] | {m['loss']:.6f} | {m['tp']} / {m['tn']} / {m['fp']} / {m['fn']} |")
    lines += ['','### Cued-target, foil and catch behavior','','| Endpoint | Target hit rate | Foil false-report rate | Catch false-report rate |','|---|---|---|---|']
    for role in ('selected','terminal'):
        ev=g[role+'_test']['by_event']; cells=[f"{ev[k]['positive_rate']:.4f} (n={ev[k]['n']})" for k in ('target','foil','catch')]; lines.append('| '+role+' | '+' | '.join(cells)+' |')
    lines += ['','### Native baseline conditions','','| Endpoint | B | BA | AUC | n |','|---|---|---|---|---|']
    for role in ('selected','terminal'):
        for k,m in g[role+'_test']['by_B'].items(): lines.append(f"| {role} | {k} | {m['balanced_accuracy']:.4f} | {m['auc']:.4f} | {m['n']} |")
    lines += ['','Uncertainty uses500bootstrap replicates of independent physical scenes, stratified byB×label. An all-positive classifier produces a degenerate BA interval[0.5,0.5]; this does **not** mean certainty about underlying representation or future performance. AUC intervals remain relevant. Single-seed, same-geometry, short-budget results do not establish reproducibility or absence of learnability.']
    lines += ['','### Endpoint computation integrity','', 'Independent saved-prediction BA/AUC replay, native label/length checks, no scene-hash overlap across splits, all Adam counters equal checkpoint update count, and CPU-vs-saved-MPS prediction parity passed. Full numerical receipt: saved_artifact_verification.json.', 'The fresh terminal endpoint had only7.8125% exactly-zero dense GELU activations on the2-trial audit and retained nonzero gradients in all module groups. Therefore the original tiny-set saturation diagnosis does **not** establish the cause of fresh-stream generalization failure, and says nothing causal about prior KDA/GRU runs.']
else:
    lines += ['','## Generalization','',g['reason']]
lines += ['','## Inputs and architecture','', 'Native ±90renderer untouched:100×100RGB, every29/37/45frame, B12/20/28, exact cue/gap/dot/report timing and target/foil/catch law. Model receives images only. There is no cue crop, event boundary, privileged side, hand-coded optical flow or supplied relational rule. Length-homogeneous batches contain no sequence padding; no hidden label-bearing mask exists.','', 'Learned stride-one3×3×3-equivalent convolution3→8 precedes spatial reduction. Learned5×5patch8→24 and2×2patch24→48 produce100tokens/frame. Two axial temporal-then-spatial self-attention blocks (width48,4heads) expose all retained time tokens; learned temporal attention pooling followed by4800→128→2MLP outputs finalCE. Details/equations in PROTOCOL.md. Spatial aggregation is lossy despite native-resolution input; no information-preservation or biological-plausibility claim.','', '## Budget, checks and artifacts','',f"Original nonrenewable budget1800s; worker result completed at{r['elapsed_seconds']:.2f}s, saved-artifact verification at{v['elapsed']:.2f}s. One MPS worker at a time; Torch/numerical CPUthreads1. Corrected worker reused original absolute deadline. No cloud, prior model loads or external modifications. All new checkpoints are generated solely by this experiment.",'','CPU test was observed failing before implementation, then1passed in2.01s: direct-renderer equality, labels, batch/single inference, first/lastframe gradients, wholebatch/microbatch gradient parity(max error1.07e−6), everyparameter gradient and optimizer update. MPS profile independently confirmed allparameter updates and input gradients across everyframe. These are pathway checks, not learning claims.','', 'Files: control.py; run_control.py; optimizer_correction.py; test_control.py; localize_failure.py; verify_saved.py; finalize_report.py; PROTOCOL.md; VERIFICATION.md; budget/progress/scene-manifest/check/selection/result JSON; fixed-set and held-out predictions; original/corrected fixed-set checkpoints and selected/terminal fresh checkpoints. See result.json for complete machine-readable metrics.','', '## Interpretation','', 'The fixed-set diagnostic demonstrates that this conventional network can use its gradient path to fit native movies after an optimizer correction. It does not establish learned native cue-motion comparison on unseen trials. The held-out endpoint metrics above determine that question; negative results are limited to this architecture, optimizer recipe, one seed and finite exposure. No claim that all neural networks fail, or that an unchanged task is unsolvable, is supported.']
(O/'REPORT.md').write_text('\n'.join(lines)+'\n')
(O/'JOURNAL.md').write_text('# Neural positive-control journal\n\n'+'\n'.join(lines[2:15])+'\n\nOriginal deadline retained. Read REPORT.md and saved_artifact_verification.json for verified final results. No training continues.\n')
receipt={'report_elapsed_seconds':time.time()-b['start_unix'],'deadline_unix':b['deadline_unix'],'within_cap':time.time()<b['deadline_unix'],'no_training_continues':True}
(O/'completion.json').write_text(json.dumps(receipt,indent=2)); print(json.dumps(receipt)); print('\n'.join(lines[:25]))
